function julian = jday( command )

if ( nargin == 0 )
	h = findobj( 'Tag', 'jday' );
	if ( ~isempty( h ) )
		figure(h);
	else
		h0 = figure('Units','points', ...
			'Name','Date Converter', ...
			'NumberTitle','off', ...
			'Position',[459 514 333 144], ...
			'Tag','jday');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'BackgroundColor',[0 0 0], ...
			'ForegroundColor',[1 1 1], ...
			'HorizontalAlignment','left', ...
			'Position',[20 80 30 20], ...
			'String','Day', ...
			'Style','text', ...
			'Tag','StaticText1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'BackgroundColor',[0 0 0], ...
			'ForegroundColor',[1 1 1], ...
			'HorizontalAlignment','left', ...
			'Position',[20 40 30 20], ...
			'String','Year', ...
			'Style','text', ...
			'Tag','StaticText1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'Position',[60 80 50 20], ...
			'Style','edit', ...
			'Tag','day1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'Position',[60 40 50 20], ...
			'Style','edit', ...
			'Tag','year1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'FontName','Monaco', ...
			'FontSize',18, ...
			'Position',[130 80 60 39], ...
			'String','=>', ...
			'Callback', 'jday(1)', ...
			'Tag','Pushbutton1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'Position',[260 100 50 20], ...
			'Style','edit', ...
			'Tag','month2');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'Position',[260 60 50 20], ...
			'Style','edit', ...
			'Tag','day2');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'BackgroundColor',[0 0 0], ...
			'ForegroundColor',[1 1 1], ...
			'HorizontalAlignment','left', ...
			'Position',[210 100 40 20], ...
			'String','Month', ...
			'Style','text', ...
			'Tag','StaticText1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'BackgroundColor',[0 0 0], ...
			'ForegroundColor',[1 1 1], ...
			'HorizontalAlignment','left', ...
			'Position',[210 60 40 20], ...
			'String','Day', ...
			'Style','text', ...
			'Tag','StaticText1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'Position',[260 20 50 20], ...
			'Style','edit', ...
			'Tag','year2');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'BackgroundColor',[0 0 0], ...
			'ForegroundColor',[1 1 1], ...
			'HorizontalAlignment','left', ...
			'Position',[210 20 40 20], ...
			'String','Year', ...
			'Style','text', ...
			'Tag','StaticText1');
		h1 = uicontrol('Parent',h0, ...
			'Units','points', ...
			'FontName','Monaco', ...
			'FontSize',18, ...
			'Position',[130 20 60 39], ...
			'String','<=', ...
			'Callback', 'jday(2)', ...
			'Tag','Pushbutton1');
	end;
		
elseif ( command == 1 )
	%disp('1');
	fig = gcf;		
	day1 = str2num(get(findobj( fig, 'Tag', 'day1' ), 'String' ) );
	year1 = str2num(get(findobj( fig, 'Tag', 'year1' ), 'String' ) );
	if (isempty(year1))
		year1 = 1999;
	end;
	
	date1 = datenum( year1, 0, day1 );
	
	year2 = datestr( date1, 10 );
	month2 = datestr(date1, 3 );
	day2 = datestr(date1, 7 );
	
	set( findobj(fig, 'Tag', 'year2'), 'String', year2 );
	set( findobj(fig, 'Tag', 'month2'), 'String', month2 );
	set( findobj(fig, 'Tag', 'day2'), 'String', day2 );
	
elseif ( command == 2 )
	fig = gcf;		
	day2 = str2num(get( findobj( fig, 'Tag', 'day2' ), 'String' ));
	year2 = str2num(get( findobj( fig, 'Tag', 'year2' ), 'String' ));
	month2 = get( findobj( fig, 'Tag', 'month2' ), 'String' );
	if (isempty(year2))
		year2 = 1999;
	end;
	
	if ( length( month2 ) < 3 )
		month2 = str2num( month2 );
	elseif strncmp(month2, 'Jan', 3) | strncmp(month2, 'jan', 3 ) 
		month2 = 1;
	elseif strncmp(month2, 'Feb', 3) | strncmp(month2, 'feb', 3 ) 
		month2 = 2;
	elseif strncmp(month2, 'Mar', 3) | strncmp(month2, 'mar', 3 ) 
		month2 = 3;
	elseif strncmp(month2, 'Apr', 3) | strncmp(month2, 'apr', 3 ) 
		month2 = 4;
	elseif strncmp(month2, 'May', 3) | strncmp(month2, 'may', 3 ) 
		month2 = 5;
	elseif strncmp(month2, 'Jun', 3) | strncmp(month2, 'jun', 3 ) 
		month2 = 6;
	elseif strncmp(month2, 'Jul', 3) | strncmp(month2, 'jul', 3 ) 
		month2 = 7;
	elseif strncmp(month2, 'Aug', 3) | strncmp(month2, 'aug', 3 ) 
		month2 = 8;
	elseif strncmp(month2, 'Sep', 3) | strncmp(month2, 'sep', 3 ) 
		month2 = 9;
	elseif strncmp(month2, 'Oct', 3) | strncmp(month2, 'oct', 3 ) 
		month2 = 10;
	elseif strncmp(month2, 'Nov', 3) | strncmp(month2, 'nov', 3 ) 
		month2 = 11;
	elseif strncmp(month2, 'Dec', 3) | strncmp(month2, 'dec', 3 ) 
		month2 = 12;
	end;


	date2 = datenum( year2, month2, day2 );
	
	year1 = datestr( date2, 10 );
	day1 = date2 - datenum( str2num( year1 ), 0, 0 );
	day1 = num2str(day1);
	set( findobj( fig, 'Tag', 'year1'), 'String', year1 );
	set( findobj( fig, 'Tag', 'day1'), 'String', day1 );
else
	year = datestr( command, 10 );
	julian = floor(command - datenum( str2num( year ), 0, 0 ));
	julian = num2str(julian);
	while (length(julian) < 3 )
		julian = [ '0' julian ];
	end;
	
end;


