function Hd = junk
%JUNK Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.7 and the Signal Processing Toolbox 6.10.
%
% Generated on: 29-Jun-2009 16:24:34
%

Fstop = 300;    % Stopband Frequency
Fpass = 1000;   % Passband Frequency
Astop = 60;     % Stopband Attenuation (dB)
Apass = 1;      % Passband Ripple (dB)
Fs    = 10000;  % Sampling Frequency

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', 'stopband');



% [EOF]
