function S_gnd_vec = lowpass_power(S_gnd_vec)
% Run a lowpass filter in the ground power to remove oscillations

% By Daniel Golden (dgolden1 at stanford dot edu)
% $Id$

%
% M-File generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
%
% Generated on: 10-Apr-2008 16:06:44
%

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 1/3;  % Sampling Frequency, samples per km

Fpass = 1/100;           % Passband Frequency
Fstop = 1/50;            % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
% Hd = dfilt.dffir(b);

%% Screw that; just use a running average filter
windowsize = 100;
for kk = 1:size(S_gnd_vec)
	S_gnd_vec(kk,:) = filter(ones(1, windowsize), 1, S_gnd_vec(kk,:));
end
