function Hd = generate_hp_filter(Fs)
% Hd = generate_hp_filter(Fs)
%GENERATE_HP_FILTER Returns a discrete-time filter object.
% Fs in Hz

%
% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 26-Aug-2010 17:00:27
%

Fstop = 300;         % Stopband Frequency
Fpass = 400;         % Passband Frequency
Astop = 60;          % Stopband Attenuation (dB)
Apass = 0.5;         % Passband Ripple (dB)

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);

Hd = design(h, 'cheby2', ...
    'MatchExactly', 'stopband');



% [EOF]
