function spec_amp = get_amp_from_spec(img_filename)
% Function that takes in a spectrogram image generated by VLFTool and makes
% an amplitude matrix from the lower spectrogram

% By Daniel Golden (dgolden1 at stanford dot edu) January 2007
% $Id$

%% Setup
error(nargchk(1, 1, nargin));

addpath('../synoptic_summary_emission_characterizer');

global spec_x_min spec_x_max spec_y_min spec_y_max

img = imread(img_filename); % Load image
ecg_set_spec_globals(img); % Get, among other things, the edges of the relevant part of the spectrogram

%% Get image values
spec_amp = zeros(spec_y_max - spec_y_min + 1, spec_x_max - spec_x_min + 1);
pixels = zeros(numel(spec_amp), 2);

emission_mask = zeros(size(spec_amp));
count = 1;
for xx = spec_x_min:spec_x_max
	for yy = spec_y_min:spec_y_max
		pixels(count, :) = [yy, xx];
		emission_mask(yy, xx) = 1;
		count = count + 1;
	end
end

[intensities, MSEs] = ecg_get_intensities_from_pix(fliplr(pixels), img);

% intensities(MSEs > 10) = NaN;

spec_amp(:) = intensities;
