function Hd = power_line_filter(Fs)
%POWER_LINE_FILTER Returns a discrete-time filter object.
% 
% INPUTS
% Fs: sampling frequency (in Hz)

%
% M-File generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
%
% Generated on: 06-Sep-2007 16:02:07
%

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
if ~exist('Fs', 'var'), Fs = 10000; end  % Sampling Frequency

Fstop = 500;         % Stopband Frequency
Fpass = 1000;        % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
